import '../../style/globals.css';
import { Roboto } from 'next/font/google';
import { ReactNode } from 'react';

const roboto = Roboto({
   weight: ['100', '300', '400', '500', '700', '900'],
   subsets: ['latin'],
   variable: '--font-roboto',
   display: 'swap',
});

export const metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
};

interface RootLayoutProps {
   children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
   return (
      <html lang="pt-br" className={roboto.className}>
         <body className='bg-gray-50 dark:bg-[#23272F]'>{children}</body>
      </html>
   );
}
