import '../../style/globals.css';
import { Roboto, Roboto_Serif, Lora, Roboto_Mono } from 'next/font/google';
import { ReactNode } from 'react';

const roboto = Roboto({
   weight: ['100', '300', '400', '500', '700', '900'],
   subsets: ['latin'],
   variable: '--font-roboto',
   display: 'swap',
});

const robotoMono = Roboto_Mono({
   weight: ['100', '200', '300', '400', '500', '600', '700'],
   subsets: ['latin'],
   variable: '--font-roboto-mono',
   display: 'swap',
});

export const metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
};

interface RootLayoutProps {
   children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
   return (
      <html
         lang="pt-br"
         className={`${roboto.variable} ${robotoMono.variable}`}
      >
         <body className="bg-gray-50 dark:bg-[#23272F] font-primary">
            {children}
         </body>
      </html>
   );
}
